Use a --changeLogFile arg in docs that works with generateChangeLog (#145)
Update the `--changeLogFile` argument in `README.md` to work with the `generateChangeLog` command. If the argument is `changelog.sql`, then `generateChangeLog` will fail with the below error.

```
[2023-05-17 17:36:57] SEVERE [liquibase.integration] Serializing changelog as sql requires a file name in the format *.databaseType.sql. Example: changelog.h2.sql. Passed: changelog.sql
liquibase.exception.CommandExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: liquibase.exception.UnexpectedLiquibaseException: Serializing changelog as sql requires a file name in the format *.databaseType.sql. Example: changelog.h2.sql. Passed: changelog.sql
	at liquibase.command.CommandScope.execute(CommandScope.java:235)
	at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:55)
	at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:24)
```