Changes databasechangelog sql to use legacy mode
When liquibase starts the very first time, the `databasechangelog` and `databasechangeloglock` are created using the default configuration which enforces object quoting strategy to LEGACY (this is not configurable)

However, when running a changelog that enforces a different quoting strategy (for instance `ALL`) this strategy overrides the default, and future interactions with the liquibase changelog tables will use the new strategy, thus resulting in errors like:

```
Unexpected error running Liquibase: Error executing SQL SELECT MAX("ORDEREXECUTED") FROM "myschema"."databasechangelog": ERROR: column "ORDEREXECUTED" does not exist
  Position: 12
liquibase.exception.UnexpectedLiquibaseException: liquibase.exception.DatabaseException: Error executing SQL SELECT MAX("ORDEREXECUTED") FROM "myschema"."databasechangelog": ERROR: column "ORDEREXECUTED" does not exist
  Position: 12
	at liquibase.sqlgenerator.core.MarkChangeSetRanGenerator.generateSql(MarkChangeSetRanGenerator.java:99)
	at liquibase.sqlgenerator.core.MarkChangeSetRanGenerator.generateSql(MarkChangeSetRanGenerator.java:25)
	at liquibase.sqlgenerator.SqlGeneratorChain.generateSql(SqlGeneratorChain.java:30)
	at liquibase.sqlgenerator.SqlGeneratorFactory.generateSql(SqlGeneratorFactory.java:222)
	at liquibase.executor.AbstractExecutor.applyVisitors(AbstractExecutor.java:25)
	at liquibase.executor.jvm.JdbcExecutor.access$600(JdbcExecutor.java:40)
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:384)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:59)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:131)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:111)
	at liquibase.changelog.StandardChangeLogHistoryService.setExecType(StandardChangeLogHistoryService.java:388)
	at liquibase.database.AbstractJdbcDatabase.markChangeSetExecStatus(AbstractJdbcDatabase.java:1133)
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:64)
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:83)
	at liquibase.Liquibase.update(Liquibase.java:202)
	at liquibase.Liquibase.update(Liquibase.java:179)
	at liquibase.Liquibase.update(Liquibase.java:334)
	at liquibase.Liquibase.updateTestingRollback(Liquibase.java:1224)
	at liquibase.Liquibase.updateTestingRollback(Liquibase.java:1215)
	at liquibase.integration.commandline.Main.doMigration(Main.java:1585)
	at liquibase.integration.commandline.Main.run(Main.java:279)
	at liquibase.integration.commandline.Main.main(Main.java:157)
Caused by: liquibase.exception.DatabaseException: Error executing SQL SELECT MAX("ORDEREXECUTED") FROM "myschema"."databasechangelog": ERROR: column "ORDEREXECUTED" does not exist
  Position: 12
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:72)
	at liquibase.executor.jvm.JdbcExecutor.query(JdbcExecutor.java:145)
	at liquibase.executor.jvm.JdbcExecutor.query(JdbcExecutor.java:153)
	at liquibase.executor.jvm.JdbcExecutor.queryForObject(JdbcExecutor.java:161)
	at liquibase.executor.jvm.JdbcExecutor.queryForObject(JdbcExecutor.java:176)
	at liquibase.executor.jvm.JdbcExecutor.queryForInt(JdbcExecutor.java:197)
	at liquibase.executor.jvm.JdbcExecutor.queryForInt(JdbcExecutor.java:192)
	at liquibase.changelog.StandardChangeLogHistoryService.getNextSequenceValue(StandardChangeLogHistoryService.java:413)
	at liquibase.sqlgenerator.core.MarkChangeSetRanGenerator.generateSql(MarkChangeSetRanGenerator.java:82)
	... 21 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: column "ORDEREXECUTED" does not exist
  Position: 12
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2468)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2211)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:309)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:311)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:297)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:274)
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:225)
	at liquibase.executor.jvm.JdbcExecutor$QueryStatementCallback.doInStatement(JdbcExecutor.java:465)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:59)
	... 29 common frames omitted
```

This commit overrides all SQL against those tables to use the legacy mode, regardless.