Fixed Oracle update error - unquoted statement
ORA-00904: "PASSWORD": invalid identifier Caused by:
java.sql.SQLSyntaxErrorException: ORA-00904: "PASSWORD": invalid
identifier  at
oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:452) at
oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:400) at
oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:884) at
oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:471) at
oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:199) at
oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:535) at
oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:197) at
oracle.jdbc.driver.T4CStatement.executeForDescribe(T4CStatement.java:116
5) at
oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.
java:1444) at
oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.
java:1662) at
oracle.jdbc.driver.OracleStatement.executeQuery(OracleStatement.java:195
8) at
oracle.jdbc.driver.OracleStatementWrapper.executeQuery(OracleStatementWr
apper.java:1695) at
liquibase.snapshot.jvm.ColumnSnapshotGenerator.readColumn(ColumnSnapshot
Generator.java:137) at
liquibase.snapshot.jvm.ColumnSnapshotGenerator.snapshotObject(ColumnSnap
shotGenerator.java:53) ... 21 more