[CORE-1254] Fix OSGiResourceAccessor failing due to javax.activation
Add optional import on javax.activation package, avoiding the
NoClassDefFoundError error in OSGi environments on Java 11